/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_401
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_adc_pal_1.h"

/*******************************************************************************
 * adc_pal_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'adc_pal_1'
- type: 'adc_pal_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'adc_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_0'
- config_sets:
  - adc_pal:
    - adcPalConfig:
      - name: 'adc_pal_1_config'
      - readOnly: 'true'
      - sampleTicks: '30'
      - extensionName: 'adc_pal_1_extensionConfig'
      - adcClkDiv: 'ADC_CLK_DIVIDE_1'
      - adcResolution: 'ADC_RESOLUTION_12BIT'
      - adcInputClock: 'ADC_CLK_ALT_1'
      - adcVoltageRef: 'ADC_VOLTAGEREF_VREF'
      - adcSupplyMonitoringEnable: 'false'
      - adcPDBPrescaler: 'PDB_CLK_PREDIV_BY_1'
      - conversionGroupArrayName: 'adc_pal_1_groupArray'
      - conversionGroupArray:
        - 0:
          - numSetsResults: '2'
          - hwTriggerSupport: 'false'
          - triggerSource: 'TRGMUX_TRIG_SOURCE_DISABLED'
          - delayType: 'ADC_DELAY_TYPE_NO_DELAY'
          - continuousConvEn: 'true'
          - callback: 'NULL'
          - callbackUserData: 'NULL'
          - resultsName: 'adc_pal_1_results0'
          - chansArrayName: 'adc_pal_1_channelsArray0'
          - inputChannelArray:
            - 0:
              - adcInputChannel: 'ADC_INPUTCHAN_EXT12'
              - chanDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/*! @brief PAL instance information */
const adc_instance_t adc_pal_1_instance = { ADC_INST_TYPE_ADC_S32K1xx, 0u }; 

/*! @brief PAL extension */
static extension_adc_s32k1xx_t adc_pal_1_extensionConfig = { 
	.clockDivide              = ADC_CLK_DIVIDE_1,
	.resolution               = ADC_RESOLUTION_12BIT,
	.inputClock               = ADC_CLK_ALT_1,
	.voltageRef               = ADC_VOLTAGEREF_VREF,
	.supplyMonitoringEnable   = false,
	.pdbPrescaler             = PDB_CLK_PREDIV_BY_1
};

/*! @brief configuration structure */
const adc_config_t adc_pal_1_config = { 
	.groupConfigArray  = adc_pal_1_groupArray,
	.numGroups         = 1u,
	.sampleTicks       = 30u,
	.extension         = &adc_pal_1_extensionConfig
};

/*! @brief array of conversion groups */
const adc_group_config_t adc_pal_1_groupArray[1u] = {
    /* Conversion group 0 */
	{
		.inputChannelArray   = adc_pal_1_channelsArray0,
		.resultBuffer        = adc_pal_1_results0,
		.numChannels         = 1u,
		.numSetsResultBuffer = 2u,
		.hwTriggerSupport    = false,
		.triggerSource       = TRGMUX_TRIG_SOURCE_DISABLED,
		.delayType           = ADC_DELAY_TYPE_NO_DELAY,
		.delayArray          = NULL,
		.continuousConvEn    = true,
		.callback            = NULL,
		.callbackUserData    = NULL
	},
};

/*! @brief group 0: input channels array */
adc_input_chan_t adc_pal_1_channelsArray0[1u] = {
	/* 0 */  ADC_INPUTCHAN_EXT12,
};
/*! @brief group 0: results buffer */
uint16_t adc_pal_1_results0[2u];



